### ISSUE TITLE
dfm-to-xaml

### ISSUE THREAD

**Issue by mnevio** [jean-lopes/dfm-to-json#2]
Hi,

interesting project. I have an application that use delphi 7 dfm, and now want to convert it to C# WPF XAML. Is it great challenge to make such conversion? Widget mapping seems to me possible, if talking about properties only, not sure about events...

In fact, did you script all widgets, for example PageControl, which is a lot complex one?

Thanks

**Comment by jean-lopes** [comment]
Hi! 
I believe it will work, if it doesn't, please add an example (dfm) to this issue :)

**Comment by jean-lopes** [comment]
> Hi,
> 
> Is it great challenge to make such conversion? Widget mapping seems to me possible, if talking about properties only, not sure about events...

Yes, it's quite a challenge. Major factors that come to mind are:
Your delphi codebase, for instance: how much runtime form manipulation happens.

The target platform, you might end up with events that cannot be easily mapped, or even components/widget.

**Comment by mnevio** [comment]
Hi Jean,

actually, no runtime form manipulation at all.

Components may be different, but in such case maybe it is possible to use component mapping? 

Regarding events, we use restricted number of different events ( Pre $ Post events, OnClick, OnStart, OnDisplay, OnClose, OnChange...) As I see, all this events are used in WPF.

Btw. I am using events based on widget name in WPF, that is a bit unusual, but enough flexible, so expecting no problem with this. This means XAML file has no code behind on no direct referencing to c# code. It behaves similar as DFM to Delphi code.

**Comment by jean-lopes** [comment]
Hi!
Of to a good start! 

> Components may be different, but in such case maybe it is possible to use component mapping?

Yes, it is possible :) might be a lot of work still.

For events, and other info that is not loaded directly from the DFM (combo box data for instance, that can be loaded directly from the database), you can use this tool to explore your DFM and query for such instances! The original use of this library for me was actually to query our codebase forms, you can use the tool `jq` (https://stedolan.github.io/jq/) and/or any database that supports json data.

If you know your way around Haskell, you might want to use it to write the converter. It's probably easier than exporting to json, and processing it on other languages.
